export const baseFlags: string[] = [
  'Calls their parents every day',
  'Always arrives 20 minutes early',
  'Sings while cooking',
  'Never uses headphones in public',
  'Has a pet snake named Kevin',
  'Runs a meme account with 100k followers',
  'Refuses to watch movies longer than 90 minutes',
  'Talks to plants before bed',
  'Keeps a spreadsheet for everything',
  'Believes cereal is a soup',
  'Owns six matching leather jackets',
  'Sleeps with the room fully lit',
  'Uses voice notes for every message',
  'Has a mystery tattoo they will not explain',
  'Insists pineapple belongs on pizza',
  'Gets competitive about board games',
  'Never misses leg day',
  'Names all their houseplants',
  'Laughs at their own jokes first',
  'Keeps hot sauce in their bag',
  'Is learning three languages at once',
  'Has perfect karaoke confidence',
  'Cannot ride a bike',
  'Brings snacks everywhere',
  'Organizes their closet by color',
  'Sends good morning texts every day',
  'Believes naps are a personality trait',
  'Only drinks sparkling water',
  'Still uses a flip phone on weekends',
  'Obsessed with true crime podcasts',
  'Hates sharing fries',
  'Wears sunglasses at night',
  'Always reads the ending first',
  'Has a side hustle selling vintage jackets',
  'Can solve a Rubik cube in under a minute',
  'Never replies with less than a paragraph',
  'Thinks clowns are cute',
  'Sleeps in full matching pajamas',
  'Only travels with carry-on',
  'Keeps receipts from every purchase',
  'Cannot function without iced coffee',
  'Loves surprise road trips',
  'Uses dating app prompts as jokes',
  'Keeps a journal of weird dreams',
  'Insists on splitting every bill exactly',
  'Owns an inflatable kayak',
  'Gives every pet a middle name',
  'Has perfect memory for birthdays',
  'Wants to move to a tiny house',
  'Collects random fridge magnets',
  'Can quote entire sitcom episodes',
  'Hums constantly when focused',
  'Never skips sunscreen',
  'Wants five dogs eventually',
  'Loses their phone daily',
  'Has never seen a superhero movie',
  'Gets emotional over cooking shows',
  'Believes in aliens strongly',
  'Writes poetry in secret',
  'Uses one giant keychain for everything',
  'Eats dessert before dinner',
  'Does 10k steps before breakfast',
  'Wears socks to sleep always',
  'Orders the same meal every time',
  'Keeps emergency glitter in a drawer',
  'Names their car',
  'Is weirdly great at trivia',
  'Has a dramatic handshake ritual',
  'Thinks voicemail is romantic',
  'Keeps tea bags in every coat pocket',
];
